{% set name = "unicorn-binance-trailing-stop-loss" %}
{% set version = "0.8.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/unicorn-binance-trailing-stop-loss-{{ version }}.tar.gz
  sha256: 643f890b8cee206b49172c697ea563c181f887d82a9e4d20375a494931b4493a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - requests
    - unicorn-binance-rest-api
    - unicorn-binance-websocket-api
  run:
    - python >=3.7
    - requests
    - ubtsl
    - unicorn-binance-rest-api
    - unicorn-binance-websocket-api

test:
  imports:
    - unicorn_binance_trailing_stop_loss
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.lucit.tech/unicorn-binance-trailing-stop-loss.html
  summary: A Python library with a command line interface for a trailing stop loss on Binance Exchange.
  description: |
    A Python library with a command line interface for a trailing stop loss and smart entry on the Binance exchange. 
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/LUCIT-Systems-and-Development/unicorn-binance-trailing-stop-loss
  doc_url: https://unicorn-binance-trailing-stop-loss.docs.lucit.tech

extra:
  recipe-maintainers:
    - oliver-zehentleitner

