{% set name = "unicorn-binance-trailing-stop-loss" %}
{% set version = "0.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/unicorn-binance-trailing-stop-loss-{{ version }}.tar.gz
  sha256: f90791c18acb5f7636ae1808e48d5b188298fe7b6f2660f285323ad120fc2fe6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - requests
    - unicorn-binance-rest-api
    - unicorn-binance-websocket-api
  run:
    - python >=3.7
    - requests
    - unicorn-binance-rest-api
    - unicorn-binance-websocket-api

test:
  imports:
    - unicorn_binance_trailing_stop_loss
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.lucit.tech/unicorn-binance-trailing-stop-loss.html
  summary: A Python library with a command line interface for a trailing stop loss on Binance Exchange.
  description: |
    A Python library with a command line interface for a trailing stop loss on Binance Exchange in a easy, fast, 
    flexible, robust and fully-featured way.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/LUCIT-Systems-and-Development/unicorn-binance-trailing-stop-loss
  doc_url: https://unicorn-binance-trailing-stop-loss.docs.lucit.tech

extra:
  recipe-maintainers:
    - oliver-zehentleitner
